[project]
name = "ioc-extractor"
version = "0.1.0"
description = "Simple tool to extract IOCs from a webpage to be used in other tools."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "requests>=2.32.5",
    "pdfplumber>=0.11.0",
]
